// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGEjvC_JsK1JJ1yzogQP413yc_HIUDkvk',
    appId: '1:661995395074:web:f0b363be366dfa6d072f1b',
    messagingSenderId: '661995395074',
    projectId: 'classpal-1307f',
    authDomain: 'classpal-1307f.firebaseapp.com',
    storageBucket: 'classpal-1307f.firebasestorage.app',
    measurementId: 'G-67L1M209D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-PsJ800AEdS1kB-B2c7bSrLnzcoax004',
    appId: '1:661995395074:android:6a9fce65118d46f5072f1b',
    messagingSenderId: '661995395074',
    projectId: 'classpal-1307f',
    storageBucket: 'classpal-1307f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqY0Tip4NrF16awzedz-Mj-qYcCMH7NE4',
    appId: '1:661995395074:ios:b7dcd430ade76e11072f1b',
    messagingSenderId: '661995395074',
    projectId: 'classpal-1307f',
    storageBucket: 'classpal-1307f.firebasestorage.app',
    iosBundleId: 'com.example.classpallFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqY0Tip4NrF16awzedz-Mj-qYcCMH7NE4',
    appId: '1:661995395074:ios:b7dcd430ade76e11072f1b',
    messagingSenderId: '661995395074',
    projectId: 'classpal-1307f',
    storageBucket: 'classpal-1307f.firebasestorage.app',
    iosBundleId: 'com.example.classpallFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGEjvC_JsK1JJ1yzogQP413yc_HIUDkvk',
    appId: '1:661995395074:web:8904491741c2022a072f1b',
    messagingSenderId: '661995395074',
    projectId: 'classpal-1307f',
    authDomain: 'classpal-1307f.firebaseapp.com',
    storageBucket: 'classpal-1307f.firebasestorage.app',
    measurementId: 'G-T3BVB03H8F',
  );
}
